INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (1, 'Administração');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (2, 'Agrimensura');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (3, 'Agroecologia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (4, 'Agroindústria');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (5, 'Agronomia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (6, 'Análise e Desenvolvimento de Sistemas');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (7, 'Antropologia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (8, 'Aquacultura');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (9, 'Arqueologia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (10, 'Arquitetura');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (11, 'Arquivística');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (12, 'Artes Cênicas');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (13, 'Artes Visuais');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (14, 'Astronomia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (15, 'Automação Industrial');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (16, 'Biblioteconomia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (17, 'Biocombustíveis');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (18, 'Bioengenharia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (19, 'Biofísica');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (20, 'Biologia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (21, 'Biologia marinha');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (22, 'Biomedicina');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (23, 'Biotecnologia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (24, 'Botânica');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (25, 'Cafeicultura');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (26, 'Ciência & Tecnologia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (27, 'Ciência da Computação');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (28, 'Ciência dos Alimentos');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (29, 'Ciência dos materiais');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (30, 'Ciência Política (ou Ciências do Estado)');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (31, 'Ciências Aeronáuticas');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (32, 'Ciências Agrárias');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (33, 'Ciências Ambientais');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (34, 'Ciências Atuariais');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (35, 'Ciências Biológicas');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (36, 'Ciências Biomoleculares');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (37, 'Ciências da Saúde');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (38, 'Ciências do Meio Aquático');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (39, 'Ciências Humanas ');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (40, 'Ciências Matemáticas da Terra');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (41, 'Ciências Naturais ');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (42, 'Ciências Náuticas');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (43, 'Ciências Sociais Licenciatura');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (44, 'Cinema');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (45, 'Comércio Exterior');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (46, 'Comunicação social');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (47, 'Construção de Edifícios');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (48, 'Construção de Estradas');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (49, 'Construção Naval');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (50, 'Contabilidade');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (51, 'Cooperativismo');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (52, 'Cosmetologia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (53, 'Dança ');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (54, 'Defesa e Gestão Estratégica Internacional');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (55, 'Desenho Industrial');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (56, 'Design de Interiores');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (57, 'Design de Jogos Digitais');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (58, 'Design de Moda');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (59, 'Design de produto');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (60, 'Design gráfico');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (61, 'Direito');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (62, 'Drenagem e Irrigação');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (63, 'Ecologia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (64, 'Economia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (65, 'Economia Doméstica');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (66, 'Editoração');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (67, 'Educação Artística ');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (68, 'Educação do Campo ');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (69, 'Educação física');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (70, 'Energias Renováveis');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (71, 'Enfermagem');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (72, 'Engenharia aeroespacial');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (73, 'Engenharia aeronáutica');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (74, 'Engenharia Agrícola');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (75, 'Engenharia Ambiental');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (76, 'Engenharia biomédica');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (77, 'Engenharia Cartográfica');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (78, 'Engenharia Civil');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (79, 'Engenharia de Alimentos');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (80, 'Engenharia de Computação');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (81, 'Engenharia de controle e automação');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (82, 'Engenharia de manufatura');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (83, 'Engenharia de Materiais');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (84, 'Engenharia de Minas');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (85, 'Engenharia de Pesca');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (86, 'Engenharia de Petróleo');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (87, 'Engenharia de Produção');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (88, 'Engenharia de Sistemas Eletrônicos');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (89, 'Engenharia de Software');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (90, 'Engenharia de Tecidos');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (91, 'Engenharia de Telecomunicações');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (92, 'Engenharia Elétrica');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (93, 'Engenharia Física');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (94, 'Engenharia Florestal');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (95, 'Engenharia geológica');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (96, 'Engenharia Industrial Madeireira');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (97, 'Engenharia Mecânica');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (98, 'Engenharia Mecatrônica');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (99, 'Engenharia Metalúrgica');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (100, 'Engenharia Militar');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (101, 'Engenharia Naval e Oceânica');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (102, 'Engenharia Nuclear');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (103, 'Engenharia Química');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (104, 'Engenharia Sanitária');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (105, 'Engenharia Têxtil');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (106, 'Enologia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (107, 'Escultura');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (108, 'Esporte e Lazer');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (109, 'Estatística');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (110, 'Eventos');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (111, 'Farmácia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (112, 'Filosofia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (113, 'Física computacional');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (114, 'Física médica');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (115, 'Física ');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (116, 'Fisioterapia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (117, 'Fonoaudiologia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (118, 'Fotografia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (119, 'Fruticultura');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (120, 'Gastronomia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (121, 'Geofísica');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (122, 'Geografia ');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (123, 'Geologia ');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (124, 'Geoprocessamento e Sensoriamento Remoto');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (125, 'Gerontologia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (126, 'Gestão Ambiental');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (127, 'Gestão Comercial');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (128, 'Gestão da Qualidade');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (129, 'Gestão da Tecnologia da Informação');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (130, 'Gestão de Petróleo e Gás');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (131, 'Gestão de Recursos Hídricos');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (132, 'Gestão de Segurança Privada');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (133, 'Gestão do Agronegócio');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (134, 'Gestão Financeira');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (135, 'Gestão Hospitalar');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (136, 'Gestão Portuária');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (137, 'Gestão Pública');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (138, 'Gravurismo');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (139, 'História');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (140, 'História da Arte');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (141, 'Horticultura');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (142, 'Hotelaria');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (143, 'Informática biomédica');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (144, 'Informática ');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (145, 'Jornalismo');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (146, 'Letras');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (147, 'Linguística');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (148, 'Logística');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (149, 'Manutenção Industrial');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (150, 'Matemática Aplicada');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (151, 'Matemática computacional');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (152, 'Matemática ');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (153, 'Mecatrônica e Mecânica de Precisão');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (154, 'Medicina');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (155, 'Medicina veterinária');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (156, 'Meliponicultura');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (157, 'Mercadologia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (158, 'Meteorologia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (159, 'Microbiologia e Imunologia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (160, 'Mineração');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (161, 'Museologia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (162, 'Música');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (163, 'Nanotecnologia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (164, 'Naturologia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (165, 'Negócios Imobiliários');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (166, 'Neurociência');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (167, 'Nutrição');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (168, 'Obstetrícia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (169, 'Oceanografia (arcaicamente referido como Ciência dos Mares)');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (170, 'Odontologia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (171, 'Oftálmica');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (172, 'Ordenamento do Território');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (173, 'Paisagismo');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (174, 'Pedagogia ');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (175, 'Pintura');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (176, 'Processamento de Dados');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (177, 'Processos Escolares');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (178, 'Processos Metalúrgicos');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (179, 'Produção Audiovisual');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (180, 'Produção Cultural');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (181, 'Produção de Aguardente');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (182, 'Produção de Laticínios');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (183, 'Produção de Materiais Plásticos');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (184, 'Produção Fonográfica');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (185, 'Produção Sucroalcooeira');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (186, 'Produção Têxtil');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (187, 'Psicologia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (188, 'Publicidade & Propaganda');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (189, 'Química ambiental');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (190, 'Química industrial');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (191, 'Química ');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (192, 'Quiropraxia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (193, 'Radiologia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (194, 'Recursos Humanos');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (195, 'Redes de Computadores');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (196, 'Redes de Telecomunicações');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (197, 'Relações Internacionais');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (198, 'Relações Públicas');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (199, 'Saneamento Ambiental');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (200, 'Saúde Coletiva');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (201, 'Secretariado');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (202, 'Segurança da Informação');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (203, 'Segurança no Trabalho');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (204, 'Segurança Pública');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (205, 'Serviço Social');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (206, 'Silvicultura');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (207, 'Sistemas Biomédicos');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (208, 'Sistemas Biomédicos');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (209, 'Sistemas de Informação');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (210, 'Sistemas de Navegação Fluvial');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (211, 'Sistemas Elétricos');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (212, 'Sistemas Embarcados');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (213, 'Sistemas para Internet');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (214, 'Sociologia ');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (215, 'Teatro ');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (216, 'Telemática');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (217, 'Teologia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (218, 'Terapia ocupacional');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (219, 'Transporte Aéreo');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (220, 'Transporte Terrestre');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (221, 'Turismologia');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (222, 'Urbanismo');
INSERT INTO public.cursosuperior (cur_id, cur_nome) VALUES (223, 'Zootecnia');