INSERT INTO public.setor (set_id, set_nome) VALUES (2, 'Água, gás e saneamento');
INSERT INTO public.setor (set_id, set_nome) VALUES (3, 'Alimentos processados');
INSERT INTO public.setor (set_id, set_nome) VALUES (4, 'Bancos');
INSERT INTO public.setor (set_id, set_nome) VALUES (5, 'Carnes e derivados');
INSERT INTO public.setor (set_id, set_nome) VALUES (6, 'Construção civil e intermediação');
INSERT INTO public.setor (set_id, set_nome) VALUES (7, 'Construção pesada e engenharia');
INSERT INTO public.setor (set_id, set_nome) VALUES (8, 'Energia elétrica');
INSERT INTO public.setor (set_id, set_nome) VALUES (9, 'Equipamentos, máquinas e peças');
INSERT INTO public.setor (set_id, set_nome) VALUES (10, 'Holdings');
INSERT INTO public.setor (set_id, set_nome) VALUES (11, 'Hotelaria e Restaurantes');
INSERT INTO public.setor (set_id, set_nome) VALUES (12, 'Imóveis comerciais e shoppings');
INSERT INTO public.setor (set_id, set_nome) VALUES (13, 'Indústrias de alimentos');
INSERT INTO public.setor (set_id, set_nome) VALUES (14, 'Indústrias em geral');
INSERT INTO public.setor (set_id, set_nome) VALUES (15, 'Materiais diversos');
INSERT INTO public.setor (set_id, set_nome) VALUES (16, 'Mineração');
INSERT INTO public.setor (set_id, set_nome) VALUES (17, 'Negócios de lazer e eventos');
INSERT INTO public.setor (set_id, set_nome) VALUES (18, 'Papel e madeira');
INSERT INTO public.setor (set_id, set_nome) VALUES (19, 'Petróleo, gás e combustíveis');
INSERT INTO public.setor (set_id, set_nome) VALUES (20, 'Química e petroquímica');
INSERT INTO public.setor (set_id, set_nome) VALUES (21, 'Roupas, calçados e acessórios');
INSERT INTO public.setor (set_id, set_nome) VALUES (22, 'Serviços diversos');
INSERT INTO public.setor (set_id, set_nome) VALUES (23, 'Serviços financeiros');
INSERT INTO public.setor (set_id, set_nome) VALUES (24, 'Setor de educação');
INSERT INTO public.setor (set_id, set_nome) VALUES (25, 'Setor de saúde');
INSERT INTO public.setor (set_id, set_nome) VALUES (26, 'Setor de seguros');
INSERT INTO public.setor (set_id, set_nome) VALUES (27, 'Setor de transporte');
INSERT INTO public.setor (set_id, set_nome) VALUES (28, 'Siderurgia e metalurgia');
INSERT INTO public.setor (set_id, set_nome) VALUES (29, 'Tecnologia da informação');
INSERT INTO public.setor (set_id, set_nome) VALUES (30, 'Telecomunicações');
INSERT INTO public.setor (set_id, set_nome) VALUES (31, 'Têxteis');
INSERT INTO public.setor (set_id, set_nome) VALUES (32, 'Utilidades domésticas');
INSERT INTO public.setor (set_id, set_nome) VALUES (33, 'Varejo');
INSERT INTO public.setor (set_id, set_nome) VALUES (1, 'Agropecuária');